### PR TITLE
Update Darksky Datasource

### PR DESCRIPTION
**Pull request by mistadave**
# Update V1.0.1

## Changes
Updated the Darksky data-source plugin. Added possibility to change Longitude and Latitude per each query if the user want to. 
By Default the values of the data-source settings will be taken.

## Testing

For a quick setup to test have a look at the **Development** section in the README.md file. [Link](https://github.com/andig/grafana-darksky#development)

### CODE REVIEW

**Comment by daniellee** [comment]
Testing this on the latest master, I'm getting errors to do with making http requests. We made some large changes in 6.7, removing Angular services and replacing them with React ones . We changed the backendSrv to be fetch based so the response format for .headers() changed from a function to an object and this breaks your code in the [doRequest method](https://github.com/andig/grafana-darksky/blob/master/src/datasource.ts#L226). Sorry about that.

Getting this error:

```
tti-polyfill.js:4 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
    at tti-polyfill.js:4
    at new Promise (<anonymous>)
    at fetch (tti-polyfill.js:4)
    at Observable._subscribe (fetch.js:30)
    at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe (Observable.js:43)
    at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe (Observable.js:29)
    at MergeMapOperator.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call (mergeMap.js:29)
    at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe (Observable.js:24)
    at Observable.push../node_modules/rxjs/_esm5/internal/observable/ConnectableObservable.js.ConnectableObservable.connect (ConnectableObservable.js:34)
    at RefCountOperator.push../node_modules/rxjs/_esm5/internal/operators/refCount.js.RefCountOperator.call (refCount.js:19)
```

Something like this will fix it and work on 6.7.x as well as on previous versions:
```ts
let responseHeaders = response.headers;
  if (!responseHeaders) {
    return null;
  }

  // Support pre 6.7 angular HTTP rather than fetch
  if (typeof responseHeaders === 'function') {
    responseHeaders = responseHeaders();
  }
```

**Comment by mistadave** [comment]
The error "e.headers is not a function" is fixed with version 1.0.2.

Thanks for the hint of the response Header check :+1:

**Comment by daniellee** [comment]
As 1.0.1 hadn't been published and the plugin.json files for the plugin still contained the version 1.0.1, I published the update as version 1.0.1 and not 1.0.2.

**Comment by mistadave** [comment]
@daniellee  thank's for the fix :+1:
